#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run prettier ||
(
    echo '🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run npm run prettier, add changes and try commit again.';
    false;
)

npm run lint ||
(
        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
